#!/bin/sh

TIM_ID="Your TIM ID (omit domain, e.g. @rwth-aachen.de)"
P="Your VPN password"

echo $P | sudo openconnect \
  --user=${TIM_ID} \
  --passwd-on-stdin \
  --authgroup="RWTH-VPN (Full Tunnel)" \
  --pfs \
  --deflate \
  --compression=all \
  --script=/etc/openconnect/local-rwth-nameserver.sh \
  $@ \
  vpn.rwth-aachen.de
